sudo: false
language: php

php:
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

install:
    - composer self-update
    - composer install

script:
    - ./tests.sh