sudo: false
language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - nightly

matrix:
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install

script:
    - ./tests.sh